#!/usr/bin/env bash

set -e

DEFAULT_PATH="${HOME}/.mope/default"

if [ -z "$MOPE_VERSION" ]; then
	MOPE_VERSION_FILE="$(mope-version-file)"
	MOPE_VERSION="$(mope-version-file-read "$MOPE_VERSION_FILE" || true)"
fi

if [ "$MOPE_VERSION" = "system" ]; then
	echo "$MOPE_VERSION"
	exit
fi

MOPE_VERSION_PATH="${HOME}/.mope/versions/${MOPE_VERSION}"

if [ -d "$MOPE_VERSION_PATH" ]; then
	echo "$MOPE_VERSION"
else
	echo "mope: version \`$MOPE_VERSION' is not installed" >&2
	exit 1
fi