#!/usr/bin/env bash

set -e

MOPE_VERSION="$1"
MOPE_VERSION_FILE=".mono-version"

if [ -n "$MOPE_VERSION" ]; then
	mope-version-file-write "$MOPE_VERSION_FILE" "$MOPE_VERSION"
else
	mope-version-file-read "$MOPE_VERSION_FILE" ||
	{
		echo "mope: no local version configured for this directory"
		exit 1
	} >&2
fi