#!/usr/bin/env bash

set -e

[ -n "$MOPE_DEBUG" ] && set -x

# Provide mope completions
if [ "$1" = "--complete" ]; then
	echo system
	exec mope-versions --bare
fi

if [ -n "$1" ]; then
	export MOPE_VERSION="$1"
elif [ -z "$MOPE_VERSION" ]; then
	MOPE_VERSION="$(mope-version-name)"
fi

if [ "$MOPE_VERSION" = "system" ]; then
	MOPE_PATH="$(mope-which mono)"
	echo "${MOPE_PATH%/*}"
	exit
fi

MOPE_PREFIX_PATH="${MOPE_ROOT}/versions/${MOPE_VERSION}"
if [ ! -d "$MOPE_PREFIX_PATH" ]; then
	echo "mope: version \`${MOPE_VERSION}' not installed" >&2
	exit 1
fi

echo "$MOPE_PREFIX_PATH"