#!/usr/bin/env bash

set -e

[ -n "$MOPE_DEBUG" ] && set -x

version="$1"

if [ -z "$version" ]; then
	if [ -z "$MOPE_VERSION" ]; then
		echo "mope: no shell-specific version configured" >&2
		exit 1
	else
		echo "echo \"\$MOPE_VERSION\""
		exit
	fi
fi

if [ "$version" = "--unset" ]; then
	echo "unset MOPE_VERSION"
	exit 1
fi

# Make sure the specified version is installed.
mope-prefix "$version" >/dev/null

echo "export MOPE_VERSION=\"${version}\""