#!/usr/bin/env bash

set -e

if [ -n "$1" ]; then
	MOPE_VERSION="$1"
elif [ -z "$MOPE_VERSION" ]; then
	MOPE_VERSION="$(mope-version)"
fi

if [ "$MOPE_VERSION" = "system" ]; then
	MOPE_PATH="$(mope-which mono)"
	echo "${MOPE_PATH%/*}"
	exit
fi

MOPE_PREFIX_PATH="${HOME}/.mope/versions/${MOPE_VERSION}"
if [ ! -d "$MOPE_PREFIX_PATH" ]; then
	echo "mope: version \`${MOPE_VERSION}' not installed" >&2
	exit 1
fi

echo "$MOPE_PREFIX_PATH"