#!/usr/bin/env bash

set -e

MOPE_VERSION="$1"
if [ -z "$MOPE_VERSION" ]; then
	echo "usage: mope set-local VERSION" >&2
	exit 1
fi

# Make sure the specified version is installed
mope-prefix "$MOPE_VERSION" >/dev/null

echo "$MOPE_VERSION" > .mope-version