#!/usr/bin/env bash

set -e

read_version_file() {
	egrep -m 1 '[^[:space:]]' "$1"
}

find_version_file() {
	local root="$(pwd)"
	while [ -n "$root" ]; do
		if [ -e "${root}/.mope-version" ]; then
			echo "${root}/.mope-version"
			return 0
		fi
		root="${root%/*}"
	done
	return 1
}

DEFAULT_PATH="${HOME}/.mope/default"

find_default_version_file() {
	if [ -e "$DEFAULT_PATH" ]; then
		echo "$DEFAULT_PATH"
		return 0
	fi
	return 1
}

if [ -z "$MOPE_VERSION" ]; then
	MOPE_VERSION_FILE="$(find_version_file || find_default_version_file || true)"

	if [ -n "$MOPE_VERSION_FILE" ]; then
		MOPE_VERSION="$(read_version_file "$MOPE_VERSION_FILE")"
	else
		echo system > "$DEFAULT_PATH"
		MOPE_VERSION=system
	fi
fi

if [ "$MOPE_VERSION" = "system" ]; then
	echo "$MOPE_VERSION"
	exit
fi

MOPE_VERSION_PATH="${HOME}/.mope/versions/${MOPE_VERSION}"

if [ -d "$MOPE_VERSION_PATH" ]; then
	echo "$MOPE_VERSION"
else
	echo "mope: version \`$MOPE_VERSION' is not installed" >&2
	exit 1
fi