#!/usr/bin/env bash

set -e

mkdir -p "${HOME}/.mope/shims"
cd "${HOME}/.mope/shims"
rm -f *

for file in ../versions/*/bin/*; do
	shim="${file##*/}"
	cat > "$shim" <<SH
#!/usr/bin/env sh
exec mope exec $shim "\$@"
SH
	chmod +x "$shim"
done