#!/usr/bin/env bash

set -e

[ -n "$MOPE_DEBUG" ] && set -x

shopt -s nullglob

{
	for path in ${PATH//:/$'\n'}; do
		for command in "${path}/mope-"*; do
			echo "${command##*mope-}"
		done
	done
} | sort | uniq