#!/usr/bin/env bash

MOPE_VERSION="0.1.0"

set -e

resolve_link() {
	$(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
	local cwd="$(pwd)"
	local path="$1"

	while [ -n "$path" ]; do
		cd "${path%/*}"
		local name="${path##*/}"
		path="$(resolve_link "$name" || true)"
	done

	pwd
	cd "$cwd"
}

if [ -z "${MOPE_ROOT}" ]; then
	MOPE_ROOT="${HOME}/.mope"
fi
export MOPE_ROOT

libexec_path="$(abs_dirname "$0")"
export PATH="${libexec_path}:${PATH}"

command="$1"
case $command in
"" | "-h" | "--help")
	echo "mope ${MOPE_VERSION}" >&2
	echo "$(mope-help)" >&2
	;;
*)
	command_path="$(command -v "mope-$command" || true)"
	if [ -z "$command_path" ]; then
		echo "mope: no such command \`$command'" >&2
		exit 1
	fi

	shift 1
	exec "$command_path" "$@"
	;;
esac