#!/usr/bin/env bash

set -e

[ -n "$MOPE_DEBUG" ] && set -x

MOPE_VERSION_NAME="$(mope-version-name)"

if [ "$1" = "--bare" ]; then
	hit_prefix=""
	miss_prefix=""
	print_version="$MOPE_VERSION_NAME"
else
	hit_prefix="* "
	miss_prefix="  "
	print_version="$(mope-version)"
fi

for path in "${MOPE_ROOT}/versions/"*; do
	if [ -d "$path" ]; then
		version="${path##*/}"

		if [ "$version" == "$MOPE_VERSION_NAME" ]; then
			echo "${hit_prefix}${print_version}"
		else
			echo "${miss_prefix}${version}"
		fi
	fi
done