#!/usr/bin/env bash

set -e

[ -n "$MOPE_DEBUG" ] && set -x

DEFAULT_PATH="${MOPE_ROOT}/default"

root="$MOPE_DIR"
while [ -n "$root" ]; do
	if [ -e "${root}/.mono-version" ]; then
		echo "${root}/.mono-version"
		exit
	fi
	root="${root%/*}"
done

echo "$DEFAULT_PATH"