#!/usr/bin/env bash

set -e

MOPE_VERSION="$1"
VERSION_FILE="${HOME}/.mope/default"
if [ -z "$MOPE_VERSION" ]; then
	if [ -e "$VERSION_FILE" ]; then
		cat "$VERSION_FILE"
	else
		echo "No default version configured - set with: mope global <version>"
	fi
else
	# Make sure the specified version is installed
	mope-prefix "$MOPE_VERSION" >/dev/null

	echo "$MOPE_VERSION" > "$VERSION_FILE"
fi