#!/usr/bin/env bash

set -e

VERSION_FILE="$1"

if [ -e "$VERSION_FILE" ]; then
	# Read the first non-whitspace word from
	# the specified version file.
	while read -a words; do
		version="${words[0]}"
		if [ -n "$version" ]; then
			echo "$version"
			exit
		fi
	done < <( cat "$VERSION_FILE" && echo )
fi

exit 1