#!/usr/bin/env bash

set -e

[ -n "$MOPE_DEBUG" ] && set -x

MOPE_VERSION="$1"
MOPE_VERSION_FILE="${MOPE_ROOT}/default"

if [ -n "$MOPE_VERSION" ]; then
	mope-version-file-write "$MOPE_VERSION_FILE" "$MOPE_VERSION"
else
	mope-version-file-read "$MOPE_VERSION_FILE" || echo system
fi